// 루트 프로젝트 이름 설정
rootProject.name = 'logistics-system'

// 공통 모듈 추가
include 'common'
project(':common').projectDir = file('common')
//infra 서비스 포함
include 'infra:gateway-server'
project(':infra:gateway-server').projectDir = file('infra/gateway-server')

// 비즈니스 서비스 포함
include 'services:company-service'
include 'services:delivery-service'
include 'services:hub-service'
include 'services:order-service'
include 'services:product-service'
include 'services:slack-ai-service'
include 'services:user-service'

project(':services:company-service').projectDir = file('services/company-service')
project(':services:delivery-service').projectDir = file('services/delivery-service')
project(':services:hub-service').projectDir = file('services/hub-service')
project(':services:order-service').projectDir = file('services/order-service')
project(':services:product-service').projectDir = file('services/product-service')
project(':services:slack-ai-service').projectDir = file('services/slack-ai-service')
project(':services:user-service').projectDir = file('services/user-service')
