server:
  port: 19096

message:
  exchange: order-exchange
  queue:
    order: orderInfo-queue

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: orders
    rabbitmq.host: localhost
    rabbitmq.port: 5672
    rabbitmq.username: guest
    rabbitmq.password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: postgres
    password: lab6
    driver-class-name: org.postgresql.Driver