server:
  port: 19098

message: "slack-ai-service dev message updated 1:35"

spring:
  jpa:

  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver