spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service # 라우트 식별자
          uri: lb://user-service # 'user-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/users/** # /users/** 경로로 들어오는 요청을 이 라우트로 처리

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hubs/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/companies/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**

        - id: slack-ai-service
          uri: lb://slack-ai-service
          predicates:
            - Path=/api/slack/**
            - Path=/api/ai/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/